### ISSUE TITLE
Récapitulatif avant DH2016

### ISSUE THREAD

**Issue by grandjeanmartin** [maladesimaginaires/intnetviz#84]
À faire au niveau développement:
- [x] Ajouter une légende #62 
- [ ] Pièces **Malades** #67
- [ ] Corriger l'affichage du **slider** (problème Firefox) #72 
- [x] Corriger un détail d'ascenseur #78
- [x] Interface en **anglais** #79
- [ ] Une ou plusieurs pièce(s) en **anglais** #80
- [x] Mettre en évidence le bouton Play/Pause #81 
- [x] Ajouter un bouton End #88
- [ ] **Icônes** des boutons #82 
- [x] Corriger _Gorgette_ dans l'_Ecole des femmes_ #86
- [x] Remodelage de l'**Affichage acte/scène/etc.** au-dessus du texte à droite du slider (et le titre reste au-dessus du slider, à gauche, sous la forme du menu déroulant déplacé #87
- [x] Créer un menu avec des boutons vers les pages du site #87 
- [x] Remettre le scrolling sur la zone network

Meta
- [x] Page **About** avec le papier et nos hagiographies personnelles #83
- [x] Créer une page **Help** #85 
- [x] Renseigner la page Help avec de la documentation sur comment utiliser les boutons/fonctions #39 #42 et expliquer la visualisation elle-même (ce que sont les arêtes, etc.).
- [x] Créer une page hébergée en github.io #91 

À faire au niveau présentation:
- [x] Découpage des parties #89
- [x] Slides #90

**Comment by ipante** [comment]
Ok, y a du pain sur la planche.
